use grocessary_store;

-- Gain an understanding of customer engagement and purchasing behavior.
-- How many unique customers have placed orders?
select * from customers;
select * from orders;
select * from order_details;
 
select distinct(customerid)
from customers
inner join orders
using (customerid);

select count(distinct(customerid))
from orders;

-- Which customers have placed the highest number of orders?

select c.name ,c.customerid ,count(o1.OrderID) as order_count
from customers c
inner join  orders o1 
on c.customerid=o1.customerid 
group by c.name ,c.customerid 
order by count(o1.OrderID) desc
limit 5; 

-- What is the total and average purchase value per customer?
select * from orders
where customerid = 3; 

select * from order_details
where orderid in (24,211,216,240);

select customerid,avg(totalprice) as Avg_purchase,sum(TotalPrice) as Total_purchase
from orders
left join order_details
using(orderid)
group by customerid;

select  distinct(orderid), Quantity,PriceEach,TotalPrice 
from order_details;

-- Who are the top 5 customers by total purchase amount?

select c.name,c.customerid,sum(o2.TotalPrice) as total_purchase
from customers c
inner join orders o1
on c.customerid=o1.customerid
inner join order_details o2
on o1.OrderID=o2.OrderID
group by customerid
order by sum(TotalPrice) desc
limit 5;


select customerid,sum(totalprice)
from orders
inner join order_details
using(orderid)
group by customerid,orderid
order by sum(TotalPrice) desc;
limit 5;


-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.

-- How many products exist in each category?
select * from products;
select * from categories;

select category_id,category_name, count(*) as no_of_products
from categories
left join products
using(category_id)
group by category_id,category_name;
 
-- What is the average price of products by category?


select category_id,category_name, avg(price) as average_price
from products
right join categories
using(category_id)
group by category_id,category_name;

-- How do product sales vary by category and supplier?
select * from supplier;
select * from order_details;


select s.sup_name,c.category_name,sum(od.TotalPrice) as Total_revenue
from order_details od
inner join products p
on od.productid=p.productid
inner join categories c
on p.category_id=c.category_id
inner join supplier s
on p.sup_id=s.sup_id
group by sup_name,category_name;

-- What is the total revenue generated by each product?

select p.productiD,p.product_name,sum(od.Totalprice) as Total_Revenue
from order_details od
right join products p
on od.productid=p.productid
group by p.productiD,p.product_name;

-- 3. Sales and Order Trends
-- Analyze business performance through orders and revenue over time.
select * from order_details;
select * from orders;

select count(o.orderid),concat(monthname(o.orderdate)," 2022") as order_month,sum(totalprice) as total_revenue
from orders o
inner join order_details od
on o.orderid=od.orderid
group by o.orderdate
order by  o.orderdate asc; 

describe orders;

set sql_safe_updates=0;

UPDATE orders
SET OrderDate = STR_TO_DATE(OrderDate, '%m/%d/%Y');

alter table orders modify column orderdate date;

-- How many orders have been placed in total?

select count(orderid)
from orders;

-- On which dates were the most orders placed?

select orderdate,count(*) as Total_order_count
from orders 
group by  orderdate
order by count(*) desc ;

-- What are the monthly trends in order volume and revenue?

select count(distinct(orderid)),monthname(orderdate) as months,sum(totalprice)
from orders
inner join order_details
using(orderid)
group by months;

select * from order_details;

-- How do order patterns vary across weekdays and weekends?
select * from orders;

select 
case
     when dayofweek(o.orderdate)in (1,7) then "weeknd"
     else "weekday"
end as day_type, count(distinct(o.orderid)) as total_orders,sum(od.totalprice)
from orders o
inner join order_details od
on o.orderid=od.orderid
group by day_type;

-- 4. Supplier Contribution
-- Identify the most active and profitable suppliers.

-- How many suppliers are there in the database?

select count(sup_id)
from supplier;

-- Which supplier provides the most products?
select * from products;
select * from supplier;

select s.sup_id,s.sup_name,count(p.productid) as no_of_products
from products p
inner join supplier s
using(sup_id)
group by sup_id
order by no_of_products desc
limit 1;

-- What is the average price of products from each supplier?

select sup_id,avg(price) as avg_price_of_products
from products
group by sup_id;

-- Which suppliers contribute the most to total product sales (by revenue)?
select * from order_details;

-- using windows function 
select sup_id,total_revenue,sup_name from
(select p.sup_id,sum(od.totalprice) as total_revenue,s.sup_name,
rank() over(order by sum(od.totalprice) desc ) as rnk
from products p
inner join order_details od
on p.productid=od.productid
inner join supplier s
on p.sup_id=s.sup_id
group by p.sup_id,s.sup_name) temp
where rnk=1;



-- 5️. Employee Performance
-- Assess how employees are handling and influencing sales.

-- How many employees have processed orders?

select * from orders;
select * from employees;
select * from order_details;

select count(distinct emp_id) as emp_with_with_orders
from orders;

-- Which employees have handled the most orders?

select emp_id,count(orderid) as total_no_of_orders
from orders
group by emp_id
order by count(orderid) desc;

select e.emp_id,count(o.orderid) as total_no_of_orders,rank() over(order by count(o.orderid) desc),e.emp_name
from employees e
inner join orders o
on e.emp_id=o.emp_id
group by e.emp_id,e.emp_name;

-- What is the total sales value processed by each employee?

select e.emp_id,sum(od.totalprice) as Total_sales,e.emp_name
from employees e
inner join orders o
on e.emp_id=o.emp_id
inner join order_details od
on o.orderid=od.orderid
group by e.emp_id,e.emp_name
order by e.emp_id,e.emp_name;


-- What is the average order value handled per employee?

select avg(od.totalprice) as avg_order,e.emp_id,e.emp_name
from employees e
inner join orders o
on e.emp_id=o.emp_id
inner join order_details od
on od.orderid=od.orderid
group by e.emp_id,e.emp_name;

/* vvimp the above average function will be incorrect for this query as it will cal the average of that order_details table only not 
for each employee, so to avoid this we do it manually by diving the sum total orders*/

select sum(od.totalprice)/count(distinct o.orderid) as avg_order,e.emp_id,e.emp_name
from employees e
inner join orders o
on e.emp_id=o.emp_id
inner join order_details od
on o.orderid=od.orderid
group by e.emp_id,e.emp_name;


